[library]
version = 2.0
authors = "Yuzo"
license = "GPL-3-or-later"
browse_url = "https://github.com/youzow3/chatbot"
description = "Chatbot, the moduler AI system"
dependencies = [
	"GLib-2.0",
	"GObject-2.0",
	"Gio-2.0",
	"Json-1.0"
]

[dependencies."GLib-2.0"]
name = "GLib"
description = "The base utility library"
docs_url = "https://docs.gtk.org/glib/"

[dependencies."GObject-2.0"]
name = "GObject"
description = "The base type system library"
docs_url = "https://docs.gtk.org/gobject/"

[dependencies."Gio-2.0"]
name = "Gio"
description = "GObject Interfaces and Objects, Networking, IPC, and I/O"
docs_url = "https://docs.gtk.org/gio/"

[dependencies."Json-1.0"]
name = "Json"
description = "JSON parser and generator"
docs_url = "https://gnome.pages.gitlab.gnome.org/json-glib/"

